POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "This Blog is a Test, and this is why that is important",
    "author": "Tessa Trying",
    "url": "https://www.testblog.com/",
    "likes": 1
}